version: '3.1'

services:
  mongo_joboffers:
    image: mongo:4.0.1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo_joboffers
    volumes:
      - ./init-usermongo.js:/docker-entrypoint-initdb.d/init-usermongo.js:ro

  mongo-express_joboffers:
    image: mongo-express
    restart: always
    ports:
      - "9001:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_joboffers:27017/
      # mongodb://{mongo-image-username}:{mongo-image-password}@{mongo-image-name}:{port}

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  redis-commander_joboffers:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
        - "9002:8081"