spring:
  data:
    mongodb:
      uri: mongodb://tomwodz:tomwodz@localhost/mongo_joboffers
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: PT3S

job-offers:
  client-offer:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connectionTimeout: 2000
          readTimeout: 2000
  offer:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend