spring:
  data:
    mongodb:
      uri: mongodb://tomwodz:tomwodz@localhost:27017/mongo_joboffers


job-offers:
  client-offer:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connectionTimeout: 2000
          readTimeout: 2000
  offer:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true